Feature/svg renderer
algorimon/git-ster pull request #15
Opened 2023-07-16 14:01 UTC by roum02

# What does this PR do?

## Type of change

- [ ] SVG renderer 테스트 환경 구성 
       - 저는 딱히 생각 나는 방도가 없어 test.html 에 그려내는 방식을 선택했는데, 혹시 더 좋은 테스트 방법이 있으면 말씀 부탁드립니다!
- [ ] TypeScript file compile to JavaScript
- [ ] Making default svg renderers
- [ ] Add test Images

2023-07-16 14:51 UTC, marshallku commented
고생 많으셨습니다!
git config에 name, email이 사내에서 쓰는 방식으로 되어있는 것 같네요...!

2023-07-16 14:53 UTC, marshallku requested changes

2023-07-16 14:53 UTC, marshallku commented on src/display/flower/flower.js
> +"use strict";
tsc 돌린 파일이 들어온 건가요??

2023-07-16 15:09 UTC, roum02 commented on src/display/flower/flower.js
> +"use strict";
git config 는 수정하였습니다. 감사합니다!

tsc 돌리면 자동으로 최상단에 생기는데, 별도의 조정이 혹시 필요할까요?

2023-07-17 13:21 UTC, marshallku commented on src/display/flower/flower.js
> +"use strict";
음...`dist`에 생기고 여긴 안 생겨야하는데 이상하네요...

```bash
find ./src -type f -name "*.js" -delete
```

한 번 실행해주실 수 있을까요?
`.gitignore` 추가로 수정해볼게요.

2023-07-19 23:59 UTC, marshallku requested changes

2023-07-19 23:59 UTC, marshallku commented on src/display/flower/flower.ts
> +    const width = 20, height = 20
```ts
const width = 20;
const height = 20;
```

위와 같이 작성하는 편이 통일성 등의 면에서 좋지 않을까요?

2023-07-19 23:59 UTC, marshallku commented on src/display/flower/flower.ts
> +        return flowerRender(Math.floor(index/7) * width, (index%7) * height, width, height)
이 return은 생략해도 될 것 같아요

2023-07-19 23:59 UTC, marshallku commented on src/display/flower/flower.ts
> +}
Prettier 설정 한 번 확인해주시겠어요...?
eof에 new line이 없네요.

2023-07-21 04:47 UTC, HyeongSeoku commented on src/display/flower/flower.js
> +var flowerRender = function (x, y, width, hight) {
단순 궁금증인데 let 대신 var 쓰신 이유가 있을까요 ?
10line 에서 재선언 때문에 쓰인것 같은데 해당 이유 말고 다른 이유가 있을까 해서 여쭤봅니다

2023-07-21 11:40 UTC, marshallku commented on src/display/flower/flower.js
> +var flowerRender = function (x, y, width, hight) {
이거 tsc가 뽑은 결과물이라서 그런 것 같아요

2023-08-15 11:20 UTC, closed without merging