Feature/background info
algorimon/git-ster pull request #29
Opened 2023-10-17 14:08 UTC by puk0806

# What does this PR do?

## Type of change

- [ ] New feature
- [ ] Bug fix
- [ ] Code improvements
- [ ] Documentation
- [ ] etc.

배경 요소들 배치 테스트 PR 입니다.

2023-10-18 22:47 UTC, marshallku requested changes

2023-10-18 22:47 UTC, marshallku commented on src/display/home/index.ts
> +};
```ts
const enum GitInfo {
  STAR = 12,
}
```
처럼 enum으로 만들어봐도 좋을 것 같네요

2023-10-18 22:47 UTC, marshallku commented on src/display/home/index.ts
> +    let render: string = "";
이미 명시적인 타입은 굳이 지정하지 않아도 되지 않을까요?

2023-10-18 22:47 UTC, marshallku commented on src/display/home/index.ts
> +        (render += handleImageRender({
`reduce()`나 `join()`도 활용해볼 수 있지 않을까요?

2023-10-18 22:47 UTC, marshallku commented on src/utils/display/backGround.ts
> +  const gressCount = Math.min(prCount / 4, MAX_GRESS_COUNT);
다른 상수들처럼 magic number도 상수로 관리해보면 좋을 것 같습니다

2023-10-23 13:02 UTC, puk0806 commented on src/utils/display/backGround.ts
> +  const gressCount = Math.min(prCount / 4, MAX_GRESS_COUNT);
혹시 무슨 뜻인지 알수있을가요???

2023-11-05 12:37 UTC, marshallku approved these changes

2023-11-05 12:37 UTC, marshallku commented on src/types/render/backGround.ts
> +};
`Record`를 사용할 수도 있을 것 같네요!

2023-11-05 12:44 UTC, merged